[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AnyApi"
version = "0.1.0"
description = "A python library which makes it easy to interact with your local Anytype Api"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Thierry Morgenthaler" }
]

dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]